version: "3.9"

services:
  users-api:
    build: ./users-api
    environment:
      - PORT=4001
      - SERVICE_NAME=users-api
      - DATABASE_URL=${USERS_DATABASE_URL}
    ports:
      - "4001:4001"
    restart: unless-stopped

  products-api:
    build: ./products-api
    environment:
      - PORT=4002
      - SERVICE_NAME=products-api
      - USERS_API_URL=http://users-api:4001
    ports:
      - "4002:4002"
    depends_on:
      - users-api
    restart: unless-stopped